// <auto-generated />
using System;
using ESport.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESport.Migrations
{
    [DbContext(typeof(ESportContext))]
    [Migration("20210520104437_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESport.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ESport.Model.Info", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("InfoId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Info");
                });

            modelBuilder.Entity("ESport.Model.Map", b =>
                {
                    b.Property<int>("MapsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("MapsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MapsId");

                    b.HasIndex("GameId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("ESport.Model.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("ESport.Model.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MapsId")
                        .HasColumnType("int");

                    b.Property<int>("Stat")
                        .HasColumnType("int");

                    b.HasKey("ScoreId");

                    b.HasIndex("MapsId");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("ESport.Model.Game", b =>
                {
                    b.HasOne("ESport.Model.Profile", null)
                        .WithOne("Game")
                        .HasForeignKey("ESport.Model.Game", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESport.Model.Info", b =>
                {
                    b.HasOne("ESport.Model.Profile", null)
                        .WithOne("Info")
                        .HasForeignKey("ESport.Model.Info", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESport.Model.Map", b =>
                {
                    b.HasOne("ESport.Model.Game", null)
                        .WithMany("Maps")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESport.Model.Score", b =>
                {
                    b.HasOne("ESport.Model.Map", "Map")
                        .WithMany("Scores")
                        .HasForeignKey("MapsId");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("ESport.Model.Game", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("ESport.Model.Map", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ESport.Model.Profile", b =>
                {
                    b.Navigation("Game");

                    b.Navigation("Info");
                });
#pragma warning restore 612, 618
        }
    }
}
